image: maven:3-amazoncorretto-11
pipelines:
  default:
    - step: &buildUpload
        name: build and upload
        caches:
          - maven
        script:
          - 'curl -s "$INFRA_API/mvn.xml" -H "x-api-key: $INFRA_API_KEY" -o settings.xml'
          - mvn -s settings.xml -Drevision=$(echo $BITBUCKET_BRANCH|sed 's/\//_/g') deploy
  branches:
    master:
      - step:
          <<: *buildUpload
          artifacts:
            - '**/target/classes/**/*.class'
      - step:
          name: sonar-scanner-cli
          image: sonarsource/sonar-scanner-cli
          script:
            - apk add curl
            - 'curl -O -s "$INFRA_API/sonar-project.properties" -H "x-api-key: $INFRA_API_KEY"'
            - /usr/bin/entrypoint.sh