version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "__TEMP__project_name_kebab_caseTEMP__"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-dm05a8pfwg2j"
s3_prefix = "__TEMP__project_name_kebab_caseTEMP__"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
