AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: '
  Example(s) of lambda(s)
  #TEMP if cookiecutter.include_dynamodb is selected_option or cookiecutter.include_http is selected_option:
  - responding to HTTP requests
  #TEMP endif
  #TEMP if cookiecutter.include_sqs_listener is selected_option:
  - handling SQS messages on an SQS queue
  #TEMP endif
  #TEMP if cookiecutter.include_s3_listener is selected_option:
  - listening to SQS-wrapped S3 events
  #TEMP endif
  '

Parameters:
    # More info about Parameters: # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
    StackEnv:
        Type: String
        Default: Dev001
        Description: Stack prefix/suffix to make resource names unique in the Tii eco-system per environment.

Globals:
    # More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
    Function:
        MemorySize: 1536
        Runtime: java11
        Timeout: 30
    Api:
        Cors:
            AllowMethods: "'GET,PUT,POST,DELETE,OPTIONS'"
            AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
            AllowOrigin: "'*'"
            AllowCredentials: "'*'"

Resources:
    #TEMP if cookiecutter.include_http is selected_option or cookiecutter.include_dynamodb is selected_option or cookiecutter.include_sqs_listener is selected_option:
    __TEMP__project_name_pascal_caseTEMP__CoreLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: __TEMP__project_name_kebab_caseTEMP__-core
            Description: "__TEMPproject_nameTEMP__ Core"
            ContentUri: __TEMP__project_name_kebab_caseTEMP__-core
            CompatibleRuntimes:
                - java11
            RetentionPolicy: Retain
        Metadata:
            BuildMethod: java11
    #TEMP endif

    #TEMP if cookiecutter.include_http is selected_option or cookiecutter.include_dynamodb is selected_option:
    __TEMP__project_name_pascal_caseTEMP__Api:
        Type: AWS::Serverless::Api
        Properties:
            StageName: !Ref StackEnv
            EndpointConfiguration:
                Type: REGIONAL
    #TEMP endif

    #TEMP if cookiecutter.include_http is selected_option:
    __TEMP__project_name_pascal_caseTEMP__Function:
        # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: __TEMP__project_name_kebab_caseTEMP__-api
            Handler: com.turnitin.__TEMP__project_name_lower_caseTEMP__.__TEMP__project_name_pascal_caseTEMP__Get
            Layers:
                - !Ref __TEMP__project_name_pascal_caseTEMP__CoreLayer
            Events:
                __TEMP__project_name_pascal_caseTEMP__HelloApi:
                    Type: Api
                    Properties:
                        RestApiId: !Ref __TEMP__project_name_pascal_caseTEMP__Api
                        Path: /hello/{who}
                        Method: GET
    #TEMP endif
    #TEMP if cookiecutter.include_dynamodb is selected_option:
    __TEMP__project_name_pascal_caseTEMP__DynamoGetFunction:
        # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: __TEMP__project_name_kebab_caseTEMP__-api
            Handler: com.turnitin.__TEMP__project_name_lower_caseTEMP__.__TEMP__project_name_pascal_caseTEMP__DynamoGet
            Layers:
                - !Ref __TEMP__project_name_pascal_caseTEMP__CoreLayer
            Environment:
                # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    dynamo_table:
                        Ref: __TEMP__project_name_pascal_caseTEMP__Table01
            Policies:
                -   DynamoDBCrudPolicy:
                      TableName:
                          Ref: __TEMP__project_name_pascal_caseTEMP__Table01
            Events:
                __TEMP__project_name_pascal_caseTEMP__DynamoGetApi:
                    Type: Api
                    Properties:
                        RestApiId: !Ref __TEMP__project_name_pascal_caseTEMP__Api
                        Path: /dynamo/{dbkey}
                        Method: GET
    __TEMP__project_name_pascal_caseTEMP__DynamoPostFunction:
        # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: __TEMP__project_name_kebab_caseTEMP__-api
            Handler: com.turnitin.__TEMP__project_name_lower_caseTEMP__.__TEMP__project_name_pascal_caseTEMP__DynamoPost
            Layers:
                - !Ref __TEMP__project_name_pascal_caseTEMP__CoreLayer
            Environment:
                # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    dynamo_table:
                        Ref: __TEMP__project_name_pascal_caseTEMP__Table01
            Policies:
                -   DynamoDBCrudPolicy:
                      TableName:
                          Ref: __TEMP__project_name_pascal_caseTEMP__Table01
            Events:
                __TEMP__project_name_pascal_caseTEMP__DyanmpPostApi:
                    Type: Api
                    Properties:
                        RestApiId: !Ref __TEMP__project_name_pascal_caseTEMP__Api
                        Path: /dynamo/{dbkey}/{value}
                        Method: POST
    #TEMP endif
    #TEMP if cookiecutter.include_sqs_listener is selected_option:
    __TEMP__project_name_pascal_caseTEMP__FunctionSQS:
        # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: __TEMP__project_name_kebab_caseTEMP__-listener
            Handler: com.turnitin.__TEMP__project_name_lower_caseTEMP__.__TEMP__project_name_pascal_caseTEMP__Sqs::handleRequest
            Layers:
                - !Ref __TEMP__project_name_pascal_caseTEMP__CoreLayer
            Environment:
                # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    dlq_bucket: plt001-dlq-dev-bucket
                    dlq_max_retries: 3
                    env_key: dev
                    presigned_url_ttl: 360000
            Events:
                __TEMP__project_name_pascal_caseTEMP__SQSEvent:
                    Type: SQS
                    Properties:
                        Queue:
                            Fn::GetAtt:
                                - __TEMP__project_name_pascal_caseTEMP__SqsQueue
                                - Arn
                        BatchSize: 10
    #TEMP endif
    #TEMP if cookiecutter.include_s3_listener is selected_option:
    __TEMP__project_name_pascal_caseTEMP__FunctionS3:
        # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: __TEMP__project_name_kebab_caseTEMP__-listener
            Handler: com.turnitin.__TEMP__project_name_lower_caseTEMP__.__TEMP__project_name_pascal_caseTEMP__S3::handleRequest
            Environment:
                # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    dlq_bucket: plt001-dlq-dev-bucket
                    dlq_max_retries: 3
                    env_key: dev
                    presigned_url_ttl: 360000
            Events:
                __TEMP__project_name_pascal_caseTEMP__SQSEvent:
                    Type: SQS
                    Properties:
                        Queue:
                            Fn::GetAtt:
                                - __TEMP__project_name_pascal_caseTEMP__SqsQueue
                                - Arn
                        BatchSize: 10
    #TEMP endif
    #TEMP if cookiecutter.include_sqs_listener is selected_option or cookiecutter.include_s3_listener is selected_option:
    __TEMP__project_name_pascal_caseTEMP__SqsQueue:
        Type: AWS::SQS::Queue
        Properties:
            VisibilityTimeout: 900
    #TEMP endif
    #TEMP if cookiecutter.include_dynamodb is selected_option:
    __TEMP__project_name_pascal_caseTEMP__Table01:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: __TEMP__project_name_pascal_caseTEMP__Table01
            BillingMode: PAY_PER_REQUEST
            AttributeDefinitions:
                -   AttributeName: pk
                    AttributeType: S
                -   AttributeName: sk
                    AttributeType: S
            KeySchema:
                -   AttributeName: pk
                    KeyType: HASH
                -   AttributeName: sk
                    KeyType: RANGE
    #TEMP endif

Outputs:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html
    __TEMP__project_name_pascal_caseTEMP__ApiRootURL:
        Description: API Gateway root URL for __TEMP__project_name_pascal_caseTEMP__ API
        Value: !Sub "https://{{ '${' }}__TEMP__project_name_pascal_caseTEMP__Api{{ '}' }}.execute-api.${AWS::Region}.amazonaws.com/${StackEnv}"

# Metadata:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/metadata-section-structure.html
# Mappings:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/mappings-section-structure.html
# Conditions:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html
