AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: '
  Example(s) of lambda(s)
  '

Parameters:
    # More info about Parameters: # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
    StackEnv:
        Type: String
        Default: Dev001
        Description: Stack prefix/suffix to make resource names unique in the Tii eco-system per environment.

Globals:
    # More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
    Function:
        MemorySize: 1536
        Runtime: java11
        Timeout: 30
    Api:
        Cors:
            AllowMethods: "'GET,PUT,POST,DELETE,OPTIONS'"
            AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
            AllowOrigin: "'*'"
            AllowCredentials: "'*'"

Resources:
    FizzBuzzFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: .
            Handler: com.turnitin.fizzbuzzlambdafunction.FizzBuzzHandler::handleRequest
            Description: Lambda function that implements FizzBuzz logic
            Environment:
                Variables:
                    STACK_ENV: !Ref StackEnv
            Events:
                FizzBuzzApi:
                    Type: Api
                    Properties:
                        Path: /fizzbuzz
                        Method: post

Outputs:
    FizzBuzzApi:
        Description: API Gateway endpoint URL for FizzBuzz function
        Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/fizzbuzz/"
    FizzBuzzFunction:
        Description: FizzBuzz Lambda Function ARN
        Value: !GetAtt FizzBuzzFunction.Arn
