AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FizzBuzz Lambda Function

Globals:
  Function:
    Timeout: 20

Resources:
  FizzBuzzFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: com.turnitin.fizzbuzzlambdafunction.FizzBuzzHandler::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        FizzBuzz:
          Type: Api
          Properties:
            Path: /fizzbuzz
            Method: post

Outputs:
  FizzBuzzApi:
    Description: API Gateway endpoint URL for Prod stage for FizzBuzz function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/fizzbuzz/"
  FizzBuzzFunction:
    Description: FizzBuzz Lambda Function ARN
    Value: !GetAtt FizzBuzzFunction.Arn
